"""Initial revision

Revision ID: f834c005245f
Revises: 
Create Date: 2024-09-01 22:23:15.949748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f834c005245f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_avg_sentiment_by_publisher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('average_sentiment', sa.Float(), nullable=True),
    sa.Column('color', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_frequency_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('associated_sentiment', sa.Float(), nullable=True),
    sa.Column('color', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_processed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('publisher_identifier', sa.String(), nullable=True),
    sa.Column('sentiment_index', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_processed')
    op.drop_table('news_frequency_words')
    op.drop_table('news_avg_sentiment_by_publisher')
    # ### end Alembic commands ###
